### ISSUE TITLE
Bundle fails with nonGlobalStepDefinitions: true

### ISSUE THREAD

**Issue by alastair-todd** [TheBrainFamily/cypress-cucumber-webpack-typescript-example#4]
I've forked this repo, brought the packages up to date, and changed the style of folder structures to be _nonGlobal_.

It is the last bit that causes the issue. When I was running as the default _old style_ things are fine.

![image](https://user-images.githubusercontent.com/595192/74463069-2109d500-4e89-11ea-858a-74372659f543.png)

**Comment by valerii-zinchenko** [comment]
I have faced the same issue. But on cypress 4.7.0 I have other error

```
     TypeError: Cannot read property 'split' of undefined
      at splitStack (http://localhost:52089/__cypress/runner/cypress_runner.js:162376:21)
      at stackWithLinesRemoved (http://localhost:52089/__cypress/runner/cypress_runner.js:162428:22)
      at Object.stackWithReplacementMarkerLineRemoved (http://localhost:52089/__cypress/runner/cypress_runner.js:162450:10)
      at preferredStackAndCodeFrameIndex (http://localhost:52089/__cypress/runner/cypress_runner.js:158121:23)
      at Object.enhanceStack (http://localhost:52089/__cypress/runner/cypress_runner.js:158133:31)
      at fail (http://localhost:52089/__cypress/runner/cypress_runner.js:156015:21)
      at Context.runnable.fn (http://localhost:52089/__cypress/runner/cypress_runner.js:156589:18)
      at callFn (http://localhost:52089/__cypress/runner/cypress_runner.js:95404:21)
      at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:52089/__cypress/runner/cypress_runner.js:95391:7)
      at http://localhost:52089/__cypress/runner/cypress_runner.js:160911:28
      at PassThroughHandlerContext.finallyHandler (http://localhost:52089/__cypress/runner/cypress_runner.js:6938:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:52089/__cypress/runner/cypress_runner.js:10384:23)
      at Promise._settlePromiseFromHandler (http://localhost:52089/__cypress/runner/cypress_runner.js:8319:31)
      at Promise._settlePromise (http://localhost:52089/__cypress/runner/cypress_runner.js:8376:18)
      at Promise._settlePromise0 (http://localhost:52089/__cypress/runner/cypress_runner.js:8421:10)
      at Promise._settlePromises (http://localhost:52089/__cypress/runner/cypress_runner.js:8501:18)
```

By debugging I am also seeing it trying to fail with error `could not clear instance from module cache`

**Comment by AaronBuxbaum** [comment]
Any word on this issue? It’s been over a year, and it’s the only thing keeping us from using Cypress

**Comment by lgandecki** [comment]
hmm, does it work when you use .feature files directly? I don't think the .features should be a requirement for using the cucumber with cypress. We are considering removing it altogether because of all the problems and maintenance  cost of keeping it

**Comment by AaronBuxbaum** [comment]
For us at least, no difference -- have tried both ways

**Comment by AaronBuxbaum** [comment]
After playing with it, I think the problem was on our end. I have it working now :)
